### ISSUE TITLE
Feature: Users enter and submit character names

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/expedition-planner#1]
## ⚙️ Feature

Users can enter and submit character names.

## 📐 Functionality

Users will be able to enter and submit character names utilizing the search input.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks
- [x] Create a component to allow users to search player names
- [x] Temporarily log player's data retrieved from the `dream-ms-api` API to console.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by apham1** [comment]
![player search](https://github.com/lisa-t-nguyen/expedition-planner/assets/22242791/68f7387c-dfba-4b37-b819-f35f51425fe0)
