### ISSUE TITLE
Feature: User can see player data (level, class, dps, etc.)

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#14]
## ⚙️ Feature

Users can see player data (level, class, dps, etc.).

## 📐 Functionality

Users will be able to see player data (level, class, dps, etc.) in party cards.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [x] Update party card component to show player data when a search is completed.

### ☁️ Server Tasks

- [x] Create an API GET to access DreamMS player data by scraping their website (e.g. https://dreamms.gg/index.php?stats={PLAYER_NAME})
    - Might be useful: https://auth0.com/blog/node-js-and-express-tutorial-building-and-securing-restful-apis/ 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by apham1** [comment]
Will be completed in #3
