### ISSUE TITLE
Feature: Implement caching for player data

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#19]
## ⚙️ Feature

Implement caching for player data.

## 📐 Functionality

Users will be able to search for a player and receive that player's most recent player data/stats saved in our database. If the player that is searched has an entry in our database that's <1 week ago then load that data. Otherwise, perform a call to the `https://dreamms.gg/index.php?stats={PLAYER_NAME}` endpoint to re-populate that data in our database.

The `playerData` `GET` request will only ever attempt to pull from the database. If it doesn't exist then the `POST` request will make the call to the `dreamms.gg` endpoint. If it exists but needs to be updated then the `PATCH` request will make the same call but update the existing entry instead.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Create a Database
    - [ ] Create a `Player` Table
        - [ ] Rows `Name`, `Class`, `Level`, `DPS`, `LastUpdated`

### ☁️ Server Tasks

- [ ] Update `dream-ms-api/index.js` to add a `POST` request to add new Player Data to the database.
- [ ] Update `dream-ms-api/index.js` to add a `PATCH` request to update existing Player Data in the database.
- [ ] Update `dream-ms-api/index.js` to update the `GET` request to attempt to pull from the `Player` Table.
    - [ ] If there is no existing record for that player, send a 404 does not exist.
    - [ ] If there is an existing record for that player, send a 200 with the player's data

### ⚡ Client Tasks

- [ ] Update `Search` component to check `playerData.lastUpdated` date
    - [ ] If it does not exist, make a POST request to the Player table and GET again.
    - [ ] Otherwise, populate that Player's data with the initial GET response's data.
        - [ ] If it's from >= 1 week ago, make a PATCH request to update the Player's data for future requests.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
