### ISSUE TITLE
Design Update: Create Wireframe on Figma

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#2]
## ⚙️ Feature

> ##### Which feature is affected by this update?

Design/wireframe is needed to better understand what work is needed to be done.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Create a design on Figma of how we want our app to look as well as the workflow/states of the app with examples.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Party Cards
- [ ] Seduce Order
- [ ] Bench
- [ ] Text Errors
- [ ] Popups

### 🧹 Clean Up
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
