### ISSUE TITLE
Feature: User can hover over role names to display a tooltip

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#23]
## ⚙️ Feature

Users can hover over role names to display a tooltip.

## 📐 Functionality

Users will be able to hover over role names to display a tooltip which will show the full name of the role as well as a detailed description of the role where applicable.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Create a Tooltip component to be used OR use built-in tooltip if one is available.

### ⚡ Client Tasks

- [ ] Create a Role -> Description Context to handle mapping the role names to the description that will be used for the tooltip. Alternative approaches for this are fine.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
