### ISSUE TITLE
Feature: Users can search for a player using API specified in a configuration file

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#25]
## ⚙️ Feature

Users can search for a player using API specified in a configuration file.

## 📐 Functionality

Calls to the API should pull from some sort of `.env`(?) file to determine the proper route. (To differentiate from API ran locally on `localhost` vs. an API hosted wherever. This should be abstracted away from where the search is performed within components.)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update the API to require an API key.
    - [ ] Calls with an incorrect or no key should be rejected with error code 401 

### ⚡ Client Tasks

- [ ] Update Search component to call the API using a link specified in a configuration file.
- [ ] Update Search component to call the API with an API key
    - [ ] Successful calls with a correct API key should work as expected
    - [ ] Unsuccessful calls due to an incorrect or no API key should handle the 401 error without removing the added player

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
