### ISSUE TITLE
Feature: User can see and click on a styled button

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#26]
## ⚙️ Feature

Users can see and click on a styled button as in the design.

## 📐 Functionality

Users will be able to see and click on a styled button as in the design. The button should have different variants/colors as well as different text displayed. The functionality of the button will be determined the component it is being used by.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [x] Create a Button component
    - [x] Button can be displayed in different colors.
    - [x] Button can contain inputted text.
    - [x] Button can call a function provided by the component it is used in. 
- [x] Update all components that use a button to use the new Button component

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
