### ISSUE TITLE
Feature: User can see popups

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#27]
## ⚙️ Feature

Users can see popup messages.

## 📐 Functionality

Users will be able to see popup messages when something happens in the application.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Create a Popup component to display a modal in the center of the screen with information provided by the component using it
- [ ] Update Search component to use the Popup component indicating when a search was not successful
    - [ ] Handle 404 Not Found
    - [ ] Handle other errors

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
