### ISSUE TITLE
Feature: Searched players will be added to the first available party slot

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#3]
## ⚙️ Feature

Searched players will be added to the first available party slot.

## 📐 Functionality

Users will be able to see their searched player added to the first available party slot.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [x] Create a component to display and manage parties
    - [x] Players will be placed within party cards (first available, max 6 per party)
- [x] Prevent users from adding players that have already been populated onto the party card(s)
- [x] Create a component to display players and player data #14 
    - [x] Display player name
    - [x] Display player data (class, level, dps, etc.)
        - [x] Assign player a role based on their class (DPS, HS, SE, SI, SED, DPS/HB, UNQUALIFIED)

### 🐘 Database Tasks

- [ ] (OPTIONAL) Add caching to player search when calling the API

### ☁️ Server Tasks

- [x] API should be called asynchronously after a player is added to the expedition

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
