### ISSUE TITLE
Feature: User can visit a link to use the app

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#31]
## ⚙️ Feature

Users can visit a link to use the app.

## 📐 Functionality

Users will be able to go to some link to use the app. The App and API need to be deployed somewhere and be able to communicate with one another.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
### ☁️ Server Tasks

- [ ] Deploy the `dream-ms-api`
- [ ] Deploy the `expedition-planner` app
- [ ] Confirm that the app is functional and communicating with the API

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
