### ISSUE TITLE
Feature: Hide DPM column when screen width shrinks to or below 1200px

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#32]
## ⚙️ Feature

DPM column should be hidden when screen width is too small to support all columns.

## 📐 Functionality

DPM column should be hidden when screen width shrinks to or below 1200px to give space for the more important player data.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Update `Player` component to hide DPM column when screen width is <=1200px
- [ ] Update `PartyCard` component to hide DPM column when screen width is <=1200px

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
