### ISSUE TITLE
Feature: User can swap players by clicking and dragging them to another slot

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#35]
## ⚙️ Feature

Users can swap players by clicking and dragging them to another slot.

## 📐 Functionality

Users will be able to swap players to another party by clicking and dragging them to another slot, empty or not. If a player is present they will swap positions. If no player is in that slot then the player being held will be moved to the end of that party.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Update Player component to support "picking up" the Player.
- [ ] Update Player component and Empty Slot component to support dropping the player on that respective slot.
- [ ] Call existing swap methods depending on where a player was dropped.
- [ ] Cancel swap action if dropped on an invalid location.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
