### ISSUE TITLE
Feature: User can optimize parties

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/expedition-planner#4]
## ⚙️ Feature

Users can optimize parties.

## 📐 Functionality

Users will be able to optimize parties by clicking on the "Optimize" button- which will sort parties based on their buffs and level.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Update party component to support taking a new list of players.
- [ ] Add optimize button component
    - [ ] Prevent users from being able to spam optimize button

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
