### ISSUE TITLE
Feature: User can swap players from one party slot to another

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#5]
## ⚙️ Feature

Users can swap players from one party slot to another.

## 📐 Functionality

Users will be able to swap players from one party slot to another both within the same party and to other parties. (occupied or not) Players should swap to the exact same slots if swapped with another player. If swapped to another party, they should be placed in the first available slot at the end.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [x] Update Player component to support movement between parties.
- [x] Update HoverOptions component to add a button for swapping players.
- [x] Update Party component to support movement between parties.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
