### ISSUE TITLE
Feature: User can reset the expedition

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#6]
## ⚙️ Feature

Users can reset the expedition.

## 📐 Functionality

Users will be able to reset the expedition and clear all parties.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Create Component to house buttons below party cards (Reset, Optimize, etc.)
    - [ ] Add Reset button and functionality
        - [ ] Call `partyManagementContext` resetParties function
    - [ ] Add confirmation modal component (TBD #27)

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
