### ISSUE TITLE
Feature: Users can see the seduce order

### ISSUE THREAD

**Issue by apham1** [lisa-t-nguyen/expedition-planner#7]
## ⚙️ Feature

Users can see the seduce order.

## 📐 Functionality

Users will be able to seed a list of players in order in which the set them for seduce.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🎨  UI Tasks

- [ ] Create a component to display a list of every player in the expedition ordered by who should be seduced first
    - [ ] Players should be automatically sorted in this list as player class/level data populates.
    - [ ] Optimize seduce order button(?)

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
