### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/expedition-planner#8]
## ✅ Task List
Commit checklist for tasks needed to complete the documentation update.
 - [ ] Work on completing README file with:
     - [ ] Title of project
     - [ ] Why this project was built
     - [ ] Technologies used
     - [ ]  Live deployment website
     - [ ] Features
     - [ ] Stretch features
     - [ ] Preview
     - [ ] Development
         - [ ] System Requirements
         - [ ] Getting Started
